version: '2'
services:
   redis-image:
      image: redis
      ports:
          - "172.18.0.1:6379:6379"
          - "127.0.0.1:6379:6379"
   mongo-image:
      image: mongo 
      ports:
        - "172.18.0.1:27017:27017"

   service-node-test-middle:
      build: ./
      volumes:
       - ./:/opt/node-test-middle
      ports:
        - "172.18.0.1:8000:8000"
        - "127.0.0.1:8000:8000"